# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'TheGoonies CTF blog'
tagline:          'Yet another CTF blog'
description:      'Thoughts, stories and ideas.'
url:              https://thegoonies.github.io
baseurl:          /

paginate:         5

# Custom vars
version:          2.0

github:
  repo:           https://github.com/thegoonies/thegoonies.github.io
  tools:          https://github.com/thegoonies/


# headline delimitor
excerpt_separator: <!--more-->
